// <auto-generated />
namespace HereAndThere.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OnePlayerManyMatches_oneMatchManyPlayers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OnePlayerManyMatches_oneMatchManyPlayers));
        
        string IMigrationMetadata.Id
        {
            get { return "201611032242500_OnePlayerManyMatches_oneMatchManyPlayers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
