// <auto-generated />
namespace HereAndThere.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_score_description : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_score_description));
        
        string IMigrationMetadata.Id
        {
            get { return "201611022000279_added_score_description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
